name: Build

on:
  pull_request:
  push:
    branches:
      - main
  merge_group:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workdir: ./client

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ${{ env.workdir }}/package-lock.json

      - name: Install dependencies
        working-directory: ${{ env.workdir }}
        run: npm ci

      - name: Lint
        working-directory: ${{ env.workdir }}
        run: npm run lint

      - name: Build
        working-directory: ${{ env.workdir }}
        env:
          PUBLIC_API_URL: ${{ secrets.PUBLIC_API_URL }}
        run: npm run build